// <auto-generated />
using System;
using Fifa2026.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fifa2026.Api.Migrations
{
    [DbContext(typeof(Fifa2026DbContext))]
    [Migration("20260630181355_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fifa2026.Api.Models.CategoriaEntrada", b =>
                {
                    b.Property<string>("PartidoId")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Disponibles")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.HasKey("PartidoId", "Categoria");

                    b.ToTable("CategoriasEntrada");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Equipo", b =>
                {
                    b.Property<string>("CodigoFifa")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("BanderaEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsAnfitrion")
                        .HasColumnType("boolean");

                    b.Property<string>("Grupo")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodigoFifa");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Estadio", b =>
                {
                    b.Property<string>("EstadioId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BanderaPaisEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Datos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Inaugurado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Superficie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EstadioId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Partido", b =>
                {
                    b.Property<string>("PartidoId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("EstadioId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<string>("Grupo")
                        .HasColumnType("text");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Jornada")
                        .HasColumnType("integer");

                    b.Property<string>("LocalCod")
                        .HasColumnType("character varying(3)");

                    b.Property<string>("NotaResultado")
                        .HasColumnType("text");

                    b.Property<string>("VisitanteCod")
                        .HasColumnType("character varying(3)");

                    b.HasKey("PartidoId");

                    b.HasIndex("EstadioId");

                    b.HasIndex("LocalCod");

                    b.HasIndex("VisitanteCod");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartidoId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ReservaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PartidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.CategoriaEntrada", b =>
                {
                    b.HasOne("Fifa2026.Api.Models.Partido", "Partido")
                        .WithMany("Entradas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Partido", b =>
                {
                    b.HasOne("Fifa2026.Api.Models.Estadio", "Estadio")
                        .WithMany("Partidos")
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fifa2026.Api.Models.Equipo", "Local")
                        .WithMany("PartidosLocal")
                        .HasForeignKey("LocalCod")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fifa2026.Api.Models.Equipo", "Visitante")
                        .WithMany("PartidosVisitante")
                        .HasForeignKey("VisitanteCod")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estadio");

                    b.Navigation("Local");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Reserva", b =>
                {
                    b.HasOne("Fifa2026.Api.Models.Partido", "Partido")
                        .WithMany("Reservas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fifa2026.Api.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Equipo", b =>
                {
                    b.Navigation("PartidosLocal");

                    b.Navigation("PartidosVisitante");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Estadio", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Partido", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Fifa2026.Api.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
